# Generated by Django 4.1.7 on 2023-02-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_itinerary', models.IntegerField()),
                ('plane_number', models.TextField()),
                ('departing_location', models.TextField()),
                ('arriving_location', models.TextField()),
                ('scheduled_takeoff', models.DateTimeField()),
                ('scheduled_landing', models.DateTimeField()),
                ('eta_landing_ts', models.IntegerField(blank=True, null=True)),
                ('actual_takeoff_ts', models.IntegerField(blank=True, null=True)),
                ('actual_landed_ts', models.IntegerField(blank=True, null=True)),
                ('last_updated_ts', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(choices=[('NONE', 'Not departed'), ('FLYING', 'Flying'), ('LANDED', 'Landed')], default='NONE')),
                ('map_link', models.URLField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.airline')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.itinerary')),
            ],
        ),
    ]
