# Generated by Django 3.2.15 on 2023-02-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_itinerary', models.IntegerField()),
                ('plane_number', models.TextField()),
                ('estimated_takeoff', models.DateTimeField()),
                ('estimated_landing', models.DateTimeField()),
                ('actual_takeoff', models.DateTimeField(null=True)),
                ('actual_landing', models.DateTimeField(null=True)),
                ('map_link', models.URLField(null=True)),
                ('status', models.TextField(choices=[('NONE', 'Not departed'), ('FLYING', 'In flight'), ('LANDED', 'Landed')], default='NONE')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.airline')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.itinerary')),
            ],
        ),
    ]
