# Generated by Django 4.1.7 on 2023-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryflight',
            name='history_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
