# Generated by Django 4.1.7 on 2023-02-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_itineraryflight_history_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone_utc_offset',
            field=models.FloatField(default=0),
        ),
    ]
