# Generated by Django 3.2.15 on 2023-02-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230218_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryflight',
            name='actual_landed_ts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryflight',
            name='actual_takeoff_ts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraryflight',
            name='status',
            field=models.TextField(choices=[('NONE', 'Not departed'), ('FLYING', 'Flying'), ('LANDED', 'Landed')], default='NONE'),
        ),
    ]
