# Generated by Django 4.1.7 on 2023-02-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230218_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryflight',
            name='last_updated_ts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
