# Generated by Django 4.1.7 on 2023-02-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_itineraryflight_last_updated_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryflight',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
