# Generated by Django 4.1.7 on 2023-02-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_itineraryflight_map_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryflight',
            old_name='estimated_landing',
            new_name='scheduled_landing',
        ),
        migrations.RenameField(
            model_name='itineraryflight',
            old_name='estimated_takeoff',
            new_name='scheduled_takeoff',
        ),
        migrations.AddField(
            model_name='itineraryflight',
            name='eta_landing_ts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
