# Generated by Django 4.1.7 on 2023-02-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_estimated_landing_itineraryflight_scheduled_landing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
