# Generated by Django 4.1.7 on 2023-02-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_itinerary_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryflight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.airline'),
        ),
        migrations.AlterField(
            model_name='itineraryflight',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.itinerary'),
        ),
    ]
